/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPendingRouteImport } from './routes/app.pending'
import { Route as AppNutritionRouteImport } from './routes/app.nutrition'
import { Route as AppIngredientsRouteImport } from './routes/app.ingredients'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppBrandsRouteImport } from './routes/app.brands'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAllergensRouteImport } from './routes/app.allergens'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAllergensRoute = AppAllergensRouteImport.update({
  id: '/allergens',
  path: '/allergens',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/allergens': typeof AppAllergensRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/ingredients': typeof AppIngredientsRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pending': typeof AppPendingRoute
  '/app/products': typeof AppProductsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/allergens': typeof AppAllergensRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/ingredients': typeof AppIngredientsRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pending': typeof AppPendingRoute
  '/app/products': typeof AppProductsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/allergens': typeof AppAllergensRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/ingredients': typeof AppIngredientsRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pending': typeof AppPendingRoute
  '/app/products': typeof AppProductsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/allergens'
    | '/app/audit'
    | '/app/branches'
    | '/app/brands'
    | '/app/categories'
    | '/app/companies'
    | '/app/ingredients'
    | '/app/nutrition'
    | '/app/pending'
    | '/app/products'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/allergens'
    | '/app/audit'
    | '/app/branches'
    | '/app/brands'
    | '/app/categories'
    | '/app/companies'
    | '/app/ingredients'
    | '/app/nutrition'
    | '/app/pending'
    | '/app/products'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/allergens'
    | '/app/audit'
    | '/app/branches'
    | '/app/brands'
    | '/app/categories'
    | '/app/companies'
    | '/app/ingredients'
    | '/app/nutrition'
    | '/app/pending'
    | '/app/products'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pending': {
      id: '/app/pending'
      path: '/pending'
      fullPath: '/app/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ingredients': {
      id: '/app/ingredients'
      path: '/ingredients'
      fullPath: '/app/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brands': {
      id: '/app/brands'
      path: '/brands'
      fullPath: '/app/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/allergens': {
      id: '/app/allergens'
      path: '/allergens'
      fullPath: '/app/allergens'
      preLoaderRoute: typeof AppAllergensRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAllergensRoute: typeof AppAllergensRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPendingRoute: typeof AppPendingRoute
  AppProductsRoute: typeof AppProductsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllergensRoute: AppAllergensRoute,
  AppAuditRoute: AppAuditRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPendingRoute: AppPendingRoute,
  AppProductsRoute: AppProductsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
