/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPromotionsRouteImport } from './routes/app.promotions'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPrintersRouteImport } from './routes/app.printers'
import { Route as AppPrintQueueRouteImport } from './routes/app.print-queue'
import { Route as AppPrintLabelsRouteImport } from './routes/app.print-labels'
import { Route as AppPrintHistoryRouteImport } from './routes/app.print-history'
import { Route as AppPrintDashboardRouteImport } from './routes/app.print-dashboard'
import { Route as AppPrintBatchRouteImport } from './routes/app.print-batch'
import { Route as AppPricesRouteImport } from './routes/app.prices'
import { Route as AppPendingRouteImport } from './routes/app.pending'
import { Route as AppNutritionRouteImport } from './routes/app.nutrition'
import { Route as AppMessageTemplatesRouteImport } from './routes/app.message-templates'
import { Route as AppLayoutsRouteImport } from './routes/app.layouts'
import { Route as AppLayoutFormatsRouteImport } from './routes/app.layout-formats'
import { Route as AppLayoutCategoriesRouteImport } from './routes/app.layout-categories'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppIngredientsRouteImport } from './routes/app.ingredients'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppBrandsRouteImport } from './routes/app.brands'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAllergensRouteImport } from './routes/app.allergens'
import { Route as AppAdminHandoverRouteImport } from './routes/app.admin-handover'
import { Route as AppPrintHistoryIdRouteImport } from './routes/app.print-history.$id'
import { Route as AppLayoutsIdRouteImport } from './routes/app.layouts.$id'
import { Route as AppIntegrationsIdRouteImport } from './routes/app.integrations.$id'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintersRoute = AppPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintQueueRoute = AppPrintQueueRouteImport.update({
  id: '/print-queue',
  path: '/print-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintLabelsRoute = AppPrintLabelsRouteImport.update({
  id: '/print-labels',
  path: '/print-labels',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintHistoryRoute = AppPrintHistoryRouteImport.update({
  id: '/print-history',
  path: '/print-history',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintDashboardRoute = AppPrintDashboardRouteImport.update({
  id: '/print-dashboard',
  path: '/print-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintBatchRoute = AppPrintBatchRouteImport.update({
  id: '/print-batch',
  path: '/print-batch',
  getParentRoute: () => AppRoute,
} as any)
const AppPricesRoute = AppPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppMessageTemplatesRoute = AppMessageTemplatesRouteImport.update({
  id: '/message-templates',
  path: '/message-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutsRoute = AppLayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutFormatsRoute = AppLayoutFormatsRouteImport.update({
  id: '/layout-formats',
  path: '/layout-formats',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutCategoriesRoute = AppLayoutCategoriesRouteImport.update({
  id: '/layout-categories',
  path: '/layout-categories',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAllergensRoute = AppAllergensRouteImport.update({
  id: '/allergens',
  path: '/allergens',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHandoverRoute = AppAdminHandoverRouteImport.update({
  id: '/admin-handover',
  path: '/admin-handover',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintHistoryIdRoute = AppPrintHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPrintHistoryRoute,
} as any)
const AppLayoutsIdRoute = AppLayoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLayoutsRoute,
} as any)
const AppIntegrationsIdRoute = AppIntegrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIntegrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin-handover': typeof AppAdminHandoverRoute
  '/app/allergens': typeof AppAllergensRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/ingredients': typeof AppIngredientsRoute
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/layout-categories': typeof AppLayoutCategoriesRoute
  '/app/layout-formats': typeof AppLayoutFormatsRoute
  '/app/layouts': typeof AppLayoutsRouteWithChildren
  '/app/message-templates': typeof AppMessageTemplatesRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pending': typeof AppPendingRoute
  '/app/prices': typeof AppPricesRoute
  '/app/print-batch': typeof AppPrintBatchRoute
  '/app/print-dashboard': typeof AppPrintDashboardRoute
  '/app/print-history': typeof AppPrintHistoryRouteWithChildren
  '/app/print-labels': typeof AppPrintLabelsRoute
  '/app/print-queue': typeof AppPrintQueueRoute
  '/app/printers': typeof AppPrintersRoute
  '/app/products': typeof AppProductsRoute
  '/app/promotions': typeof AppPromotionsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/integrations/$id': typeof AppIntegrationsIdRoute
  '/app/layouts/$id': typeof AppLayoutsIdRoute
  '/app/print-history/$id': typeof AppPrintHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin-handover': typeof AppAdminHandoverRoute
  '/app/allergens': typeof AppAllergensRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/ingredients': typeof AppIngredientsRoute
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/layout-categories': typeof AppLayoutCategoriesRoute
  '/app/layout-formats': typeof AppLayoutFormatsRoute
  '/app/layouts': typeof AppLayoutsRouteWithChildren
  '/app/message-templates': typeof AppMessageTemplatesRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pending': typeof AppPendingRoute
  '/app/prices': typeof AppPricesRoute
  '/app/print-batch': typeof AppPrintBatchRoute
  '/app/print-dashboard': typeof AppPrintDashboardRoute
  '/app/print-history': typeof AppPrintHistoryRouteWithChildren
  '/app/print-labels': typeof AppPrintLabelsRoute
  '/app/print-queue': typeof AppPrintQueueRoute
  '/app/printers': typeof AppPrintersRoute
  '/app/products': typeof AppProductsRoute
  '/app/promotions': typeof AppPromotionsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/integrations/$id': typeof AppIntegrationsIdRoute
  '/app/layouts/$id': typeof AppLayoutsIdRoute
  '/app/print-history/$id': typeof AppPrintHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin-handover': typeof AppAdminHandoverRoute
  '/app/allergens': typeof AppAllergensRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/brands': typeof AppBrandsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/ingredients': typeof AppIngredientsRoute
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/layout-categories': typeof AppLayoutCategoriesRoute
  '/app/layout-formats': typeof AppLayoutFormatsRoute
  '/app/layouts': typeof AppLayoutsRouteWithChildren
  '/app/message-templates': typeof AppMessageTemplatesRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/pending': typeof AppPendingRoute
  '/app/prices': typeof AppPricesRoute
  '/app/print-batch': typeof AppPrintBatchRoute
  '/app/print-dashboard': typeof AppPrintDashboardRoute
  '/app/print-history': typeof AppPrintHistoryRouteWithChildren
  '/app/print-labels': typeof AppPrintLabelsRoute
  '/app/print-queue': typeof AppPrintQueueRoute
  '/app/printers': typeof AppPrintersRoute
  '/app/products': typeof AppProductsRoute
  '/app/promotions': typeof AppPromotionsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/integrations/$id': typeof AppIntegrationsIdRoute
  '/app/layouts/$id': typeof AppLayoutsIdRoute
  '/app/print-history/$id': typeof AppPrintHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/redefinir-senha'
    | '/app/admin-handover'
    | '/app/allergens'
    | '/app/audit'
    | '/app/branches'
    | '/app/brands'
    | '/app/categories'
    | '/app/companies'
    | '/app/ingredients'
    | '/app/integrations'
    | '/app/layout-categories'
    | '/app/layout-formats'
    | '/app/layouts'
    | '/app/message-templates'
    | '/app/nutrition'
    | '/app/pending'
    | '/app/prices'
    | '/app/print-batch'
    | '/app/print-dashboard'
    | '/app/print-history'
    | '/app/print-labels'
    | '/app/print-queue'
    | '/app/printers'
    | '/app/products'
    | '/app/promotions'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/'
    | '/app/integrations/$id'
    | '/app/layouts/$id'
    | '/app/print-history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/app/admin-handover'
    | '/app/allergens'
    | '/app/audit'
    | '/app/branches'
    | '/app/brands'
    | '/app/categories'
    | '/app/companies'
    | '/app/ingredients'
    | '/app/integrations'
    | '/app/layout-categories'
    | '/app/layout-formats'
    | '/app/layouts'
    | '/app/message-templates'
    | '/app/nutrition'
    | '/app/pending'
    | '/app/prices'
    | '/app/print-batch'
    | '/app/print-dashboard'
    | '/app/print-history'
    | '/app/print-labels'
    | '/app/print-queue'
    | '/app/printers'
    | '/app/products'
    | '/app/promotions'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app'
    | '/app/integrations/$id'
    | '/app/layouts/$id'
    | '/app/print-history/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/redefinir-senha'
    | '/app/admin-handover'
    | '/app/allergens'
    | '/app/audit'
    | '/app/branches'
    | '/app/brands'
    | '/app/categories'
    | '/app/companies'
    | '/app/ingredients'
    | '/app/integrations'
    | '/app/layout-categories'
    | '/app/layout-formats'
    | '/app/layouts'
    | '/app/message-templates'
    | '/app/nutrition'
    | '/app/pending'
    | '/app/prices'
    | '/app/print-batch'
    | '/app/print-dashboard'
    | '/app/print-history'
    | '/app/print-labels'
    | '/app/print-queue'
    | '/app/printers'
    | '/app/products'
    | '/app/promotions'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/'
    | '/app/integrations/$id'
    | '/app/layouts/$id'
    | '/app/print-history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promotions': {
      id: '/app/promotions'
      path: '/promotions'
      fullPath: '/app/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/printers': {
      id: '/app/printers'
      path: '/printers'
      fullPath: '/app/printers'
      preLoaderRoute: typeof AppPrintersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/print-queue': {
      id: '/app/print-queue'
      path: '/print-queue'
      fullPath: '/app/print-queue'
      preLoaderRoute: typeof AppPrintQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/print-labels': {
      id: '/app/print-labels'
      path: '/print-labels'
      fullPath: '/app/print-labels'
      preLoaderRoute: typeof AppPrintLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/print-history': {
      id: '/app/print-history'
      path: '/print-history'
      fullPath: '/app/print-history'
      preLoaderRoute: typeof AppPrintHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/print-dashboard': {
      id: '/app/print-dashboard'
      path: '/print-dashboard'
      fullPath: '/app/print-dashboard'
      preLoaderRoute: typeof AppPrintDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/print-batch': {
      id: '/app/print-batch'
      path: '/print-batch'
      fullPath: '/app/print-batch'
      preLoaderRoute: typeof AppPrintBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prices': {
      id: '/app/prices'
      path: '/prices'
      fullPath: '/app/prices'
      preLoaderRoute: typeof AppPricesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pending': {
      id: '/app/pending'
      path: '/pending'
      fullPath: '/app/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/message-templates': {
      id: '/app/message-templates'
      path: '/message-templates'
      fullPath: '/app/message-templates'
      preLoaderRoute: typeof AppMessageTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/layouts': {
      id: '/app/layouts'
      path: '/layouts'
      fullPath: '/app/layouts'
      preLoaderRoute: typeof AppLayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/layout-formats': {
      id: '/app/layout-formats'
      path: '/layout-formats'
      fullPath: '/app/layout-formats'
      preLoaderRoute: typeof AppLayoutFormatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/layout-categories': {
      id: '/app/layout-categories'
      path: '/layout-categories'
      fullPath: '/app/layout-categories'
      preLoaderRoute: typeof AppLayoutCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ingredients': {
      id: '/app/ingredients'
      path: '/ingredients'
      fullPath: '/app/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brands': {
      id: '/app/brands'
      path: '/brands'
      fullPath: '/app/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/allergens': {
      id: '/app/allergens'
      path: '/allergens'
      fullPath: '/app/allergens'
      preLoaderRoute: typeof AppAllergensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin-handover': {
      id: '/app/admin-handover'
      path: '/admin-handover'
      fullPath: '/app/admin-handover'
      preLoaderRoute: typeof AppAdminHandoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/print-history/$id': {
      id: '/app/print-history/$id'
      path: '/$id'
      fullPath: '/app/print-history/$id'
      preLoaderRoute: typeof AppPrintHistoryIdRouteImport
      parentRoute: typeof AppPrintHistoryRoute
    }
    '/app/layouts/$id': {
      id: '/app/layouts/$id'
      path: '/$id'
      fullPath: '/app/layouts/$id'
      preLoaderRoute: typeof AppLayoutsIdRouteImport
      parentRoute: typeof AppLayoutsRoute
    }
    '/app/integrations/$id': {
      id: '/app/integrations/$id'
      path: '/$id'
      fullPath: '/app/integrations/$id'
      preLoaderRoute: typeof AppIntegrationsIdRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
  }
}

interface AppIntegrationsRouteChildren {
  AppIntegrationsIdRoute: typeof AppIntegrationsIdRoute
}

const AppIntegrationsRouteChildren: AppIntegrationsRouteChildren = {
  AppIntegrationsIdRoute: AppIntegrationsIdRoute,
}

const AppIntegrationsRouteWithChildren = AppIntegrationsRoute._addFileChildren(
  AppIntegrationsRouteChildren,
)

interface AppLayoutsRouteChildren {
  AppLayoutsIdRoute: typeof AppLayoutsIdRoute
}

const AppLayoutsRouteChildren: AppLayoutsRouteChildren = {
  AppLayoutsIdRoute: AppLayoutsIdRoute,
}

const AppLayoutsRouteWithChildren = AppLayoutsRoute._addFileChildren(
  AppLayoutsRouteChildren,
)

interface AppPrintHistoryRouteChildren {
  AppPrintHistoryIdRoute: typeof AppPrintHistoryIdRoute
}

const AppPrintHistoryRouteChildren: AppPrintHistoryRouteChildren = {
  AppPrintHistoryIdRoute: AppPrintHistoryIdRoute,
}

const AppPrintHistoryRouteWithChildren = AppPrintHistoryRoute._addFileChildren(
  AppPrintHistoryRouteChildren,
)

interface AppRouteChildren {
  AppAdminHandoverRoute: typeof AppAdminHandoverRoute
  AppAllergensRoute: typeof AppAllergensRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRouteWithChildren
  AppLayoutCategoriesRoute: typeof AppLayoutCategoriesRoute
  AppLayoutFormatsRoute: typeof AppLayoutFormatsRoute
  AppLayoutsRoute: typeof AppLayoutsRouteWithChildren
  AppMessageTemplatesRoute: typeof AppMessageTemplatesRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPendingRoute: typeof AppPendingRoute
  AppPricesRoute: typeof AppPricesRoute
  AppPrintBatchRoute: typeof AppPrintBatchRoute
  AppPrintDashboardRoute: typeof AppPrintDashboardRoute
  AppPrintHistoryRoute: typeof AppPrintHistoryRouteWithChildren
  AppPrintLabelsRoute: typeof AppPrintLabelsRoute
  AppPrintQueueRoute: typeof AppPrintQueueRoute
  AppPrintersRoute: typeof AppPrintersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminHandoverRoute: AppAdminHandoverRoute,
  AppAllergensRoute: AppAllergensRoute,
  AppAuditRoute: AppAuditRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppIntegrationsRoute: AppIntegrationsRouteWithChildren,
  AppLayoutCategoriesRoute: AppLayoutCategoriesRoute,
  AppLayoutFormatsRoute: AppLayoutFormatsRoute,
  AppLayoutsRoute: AppLayoutsRouteWithChildren,
  AppMessageTemplatesRoute: AppMessageTemplatesRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPendingRoute: AppPendingRoute,
  AppPricesRoute: AppPricesRoute,
  AppPrintBatchRoute: AppPrintBatchRoute,
  AppPrintDashboardRoute: AppPrintDashboardRoute,
  AppPrintHistoryRoute: AppPrintHistoryRouteWithChildren,
  AppPrintLabelsRoute: AppPrintLabelsRoute,
  AppPrintQueueRoute: AppPrintQueueRoute,
  AppPrintersRoute: AppPrintersRoute,
  AppProductsRoute: AppProductsRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
